# swagger.yaml
openapi: 3.0.0
info:
  title: API de Productos y Autenticación
  description: API para manejar la autenticación de usuarios y gestión de productos.
  version: 1.0.0
servers:
  - url: 'http://localhost:3000/api'
    description: Servidor local
paths:
  /auth/register:
    post:
      summary: Registra un nuevo usuario
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '201':
          description: Usuario registrado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Error en el registro
  /auth/login:
    post:
      summary: Inicia sesión con un usuario existente
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: Inicio de sesión exitoso
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Error en el inicio de sesión
  /products:
    get:
      summary: Obtiene todos los productos
      tags:
        - Products
      responses:
        '200':
          description: Lista de productos
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    price:
                      type: number
                    cantidad:
                      type: integer
                    SKU:
                      type: string
    post:
      summary: Agrega un nuevo producto
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
                cantidad:
                  type: integer
                SKU:
                  type: string
      responses:
        '201':
          description: Producto agregado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
  /products/{id}:
    get:
      summary: Obtiene detalles de un producto específico
      tags:
        - Products
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Detalles del producto
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  price:
                    type: number
                  cantidad:
                    type: integer
                  SKU:
                    type: string
    put:
      summary: Actualiza un producto existente
      tags:
        - Products
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
                cantidad:
                  type: integer
                SKU:
                  type: string
      responses:
        '200':
          description: Producto actualizado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
    delete:
      summary: Elimina un producto
      tags:
        - Products
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Producto eliminado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
